CREATE TABLE IF NOT EXISTS public.sr_university
(
    university_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    university_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sr_university_pkey PRIMARY KEY (university_id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.sr_university
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.sr_university
(
    university_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    university_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sr_university_pkey PRIMARY KEY (university_id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.sr_university
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.sr_university
(
    university_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    university_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sr_university_pkey PRIMARY KEY (university_id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.sr_university
    OWNER to postgres;

CREATE TABLE IF NOT EXISTS public.sr_university
(
    university_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    university_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT sr_university_pkey PRIMARY KEY (university_id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.sr_university
    OWNER to postgres;

INSERT INTO sr_university (university_name) VALUES ('University One');
INSERT INTO sr_university (university_name) VALUES ('University Two');

INSERT INTO sr_faculty (university_id, faculty_name) VALUES (1, 'Faculty One');
INSERT INTO sr_faculty (university_id, faculty_name) VALUES (1, 'Faculty Two');
INSERT INTO sr_faculty (university_id, faculty_name) VALUES (2, 'Faculty Other One');
INSERT INTO sr_faculty (university_id, faculty_name) VALUES (2, 'Faculty Other Two');

INSERT INTO sr_student (last_name, first_name, middle_name, date_of_birth,
                        passport_serial, passport_number, passport_date)

VALUES ('Last', 'First', 'Middle', '2000-04-12', '1111', '222222', '2016-04-30');

INSERT INTO sr_student_document (document_number, document_date, expired_date,
                                 student_id, faculty_id, student_form)
VALUES ('123456', '2017-09-01', '2021-05-31', 1, 1, 0);
